### ISSUE TITLE
whereami 1.2.10 crashloopbackoff

### ISSUE THREAD

**Issue by theemadnes** [GoogleCloudPlatform/kubernetes-engine-samples#337]
there's a problem with the protobufs definitions that's causing `whereami` pods to crash. working on it now. 

```kubectl -n backend logs whereami-backend-6c8d44596b-7cp95
Traceback (most recent call last):
  File "/app/app.py", line 7, in <module>
    import whereami_payload
  File "/app/whereami_payload.py", line 12, in <module>
    import whereami_pb2
  File "/app/whereami_pb2.py", line 28, in <module>
    _EMPTY = _descriptor.Descriptor(
  File "/usr/local/lib/python3.10/site-packages/google/protobuf/descriptor.py", line 313, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates```

**Comment by theemadnes** [comment]
CC: @boredabdel @mathieu-benoit @ameer00 @askmeegs 

FYI `1.2.9` still appears to work fine but once i figure this out will put in a PR and update references to the `1.2.10` images elsewhere

**Comment by theemadnes** [comment]
the PR will update the image references to `1.2.11` and i'll then update the networking samples to the same
